version: "2.0"
services:
  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis:/bitnami/redis/data

volumes:
  redis: {}
