version: "2.0"
services:
  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis:/bitnami/redis/data
  postgres:
    image: "postgres:16"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
     POSTGRES_USER: "admin"
     POSTGRES_PASSWORD: "admin"
     POSTGRES_DB: "devanewbot"

volumes:
  redis: {}
  postgres_data: {}